# Generated by Django 4.0 on 2022-01-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
    ]
