# Generated by Django 4.0 on 2022-05-21 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='deal',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 23, 13, 1, 973692)),
        ),
    ]
