# Generated by Django 4.1 on 2022-08-25 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_delete_tag_alter_deal_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 18, 7, 39, 928656)),
        ),
    ]
