# Generated by Django 4.0 on 2022-01-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_remove_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='social_network.Tag'),
        ),
    ]
