# Generated by Django 4.0 on 2022-06-07 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_delete_tag_alter_deal_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 12, 36, 51, 697269)),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initiated'), (2, 'Pending'), (3, 'Borrowed'), (4, 'Completed'), (5, 'Failed'), (6, 'Error')], default=1),
        ),
    ]
