# Generated by Django 4.0 on 2022-06-07 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_alter_deal_due_date_alter_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deal',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 13, 10, 37, 635753)),
        ),
    ]
