# Generated by Django 4.1 on 2022-08-31 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_alter_deal_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 10, 53, 39, 674013)),
        ),
    ]
