# Generated by Django 4.0 on 2022-01-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_alter_item_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='social_network.Tag'),
        ),
    ]
