# Generated by Django 4.1 on 2022-09-08 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_alter_deal_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 5, 25, 45, 478443)),
        ),
    ]
