# Generated by Django 4.0 on 2022-01-10 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_alter_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
