version: "3.9"

services:
  fraand-core:
    container_name: fraand
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    volumes:
      - ${PATH_TO_PROJECT}/pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
        test: [ "CMD-SHELL", "sh", "-c", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_NAME}"]
        interval: 1s
        timeout: 3s
        retries: 10
