version: "3.9"

services:
  fraand-core:
    container_name: fraand
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
