version: '3'

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    network_mode: host
    env_file:
      - envs/.dev_db_env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: app
    restart: always
    network_mode: host
    ports:
      - "8080:8000"
    command: python3 fraand/manage.py runserver 0.0.0.0:8000
    env_file:
      - envs/.dev_django_env
      - envs/.dev_db_env
