version: '3'

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    network_mode: host
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_PORT=5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: app
    restart: always
    network_mode: host
    ports:
      - "8080:8000"
    command: python3 fraand/manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/__pypackages__/3.9/lib/:/app/fraand/:/app/
      - SECRET_KEY=lol
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_PORT=5432
