[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Uno Yakshi", email = "uno.yakshi@e.email"},
]
dependencies = [
    "django>=4.0",
    "django-environ>=0.8.1",
    "psycopg2-binary>=2.9.3",
    "Pillow>=9.1.1",
    "django-crispy-forms>=1.14.0",
    "django-taggit>=3.0.0",
    "django-extensions>=3.1.5",
]
requires-python = ">=3.9"
license = {text = "GNU"}

[project.urls]
homepage = ""

[project.optional-dependencies]
[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=6.2.5",
    "flake8>=4.0.1",
    "black>=21.12b0",
    "pytest-django>=4.5.2",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
