"""Added User-to-Item relationship...

Revision ID: ac168244ec6b
Revises: 062796a52532
Create Date: 2023-05-21 15:15:00.676565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac168244ec6b'
down_revision = '062796a52532'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('items_owner_id_fkey'), 'items', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_owner_id_fkey'), 'items', type_='foreignkey')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###


def schema_upgrades():
    """Schema upgrade migrations go here..."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('items_owner_id_fkey'), 'items', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here..."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_owner_id_fkey'), 'items', type_='foreignkey')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
