"""Added user model...

Revision ID: 8fc39660ddf4
Revises: 58ea474ac818
Create Date: 2023-05-06 00:54:46.601181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc39660ddf4'
down_revision = '58ea474ac818'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
        sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='user_pkey'),
    )
    op.create_index('user_email_idx', 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_email_idx', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
