"""Added Tag, ItemTag models...

Revision ID: 062796a52532
Revises: 720d958185d7
Create Date: 2023-05-16 02:29:59.569509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062796a52532'
down_revision = '720d958185d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey')),
    )
    op.create_table(
        'items_tags_at',
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('items_tags_at_item_id_fkey')),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('items_tags_at_tag_id_fkey')),
        sa.PrimaryKeyConstraint('tag_id', 'item_id', name=op.f('items_tags_at_pkey')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_tags_at')
    op.drop_table('tags')
    # ### end Alembic commands ###


def schema_upgrades():
    """Schema upgrade migrations go here..."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey')),
    )
    op.create_table(
        'items_tags_at',
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('items_tags_at_item_id_fkey')),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('items_tags_at_tag_id_fkey')),
        sa.PrimaryKeyConstraint('tag_id', 'item_id', name=op.f('items_tags_at_pkey')),
    )
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here..."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_tags_at')
    op.drop_table('tags')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
